services:

  backend_ci:
    image: node:18-alpine
    container_name: shop_sphere_backend_ci
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb+srv://mdaud9062_db_user:OWMPP19JHAFBAzSO@shop-sphere.pwtcm1s.mongodb.net/?retryWrites=true&w=majority&appName=Shop-Sphere
      - JWT_SECRETKEY=ci_jwt_secret
    depends_on:
      - mongo_ci
    command: sh -c "npm ci && npm run build"
    ports:
      - "4000:3000"
    restart: 'no'
  
  frontend_ci:
    image: node:18-alpine
    container_name: shop_sphere_frontend_ci
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm ci && npm run build"
    ports:
      - "8085:5173"
    restart: 'no'

