services:
  frontend:
    container_name: jenkins_frontend
    image: node:20-alpine
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    command: sh -c "npm install && npm run build && npx serve -s build -l 8080"
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_API_URL=http://13.203.220.24:3001
    depends_on:
      - backend
    restart: always
  
  backend:
    container_name: jenkins_backend
    image: node:20-alpine
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - JWT_SECRETKEY=chintapaktamtam
      - MONGODB_URI=mongodb+srv://mdaud9062_db_user:OWMPP19JHAFBAzSO@shop-sphere.pwtcm1s.mongodb.net/?retryWrites=true&w=majority&appName=Shop-Sphere
    restart: always